{% set goname = "github.com/nbedos/citop" %}
{% set version = "0.1.2" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: 6402f352998bfcd3b8700e9771b77ff0bd53197ad035f2b7c615ee65ef874169

build:
  number: 1
  skip: true  # [win]
  script:
    - pushd {{ pkg_src }}
    - go build -ldflags "-X main.Version={{ version }}" -v -o $GOBIN/{{ name }} .       # [unix]

requirements:
  build:
    - {{ compiler("go") }} >=1.11

test:
  commands:
    - citop --version

about:
  home: https://github.com/nbedos/citop
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ pkg_src }}/LICENSE
  summary: |
    A UNIX program to monitor Continuous Integration pipelines from the command line.
    citop stands for Continous Integration Table Of Pipelines.
  dev_url: https://github.com/nbedos/citop
  doc_url: https://nbedos.github.io/citop/citop.man

extra:
  recipe-maintainers:
    - luizirber
